--
-- PostgreSQL database dump
--

\restrict mGQTcto3XvUQrP0XhjmQf7OnU7SjeYhYg35k4LgZJoWHZlCVPaL2zZ7wUrhsSRa

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actual_outcome; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.actual_outcome (
    id bigint NOT NULL,
    actual_customer_acquisition_cost numeric(10,2),
    actual_customer_retention numeric(5,2),
    actual_operational_efficiency numeric(5,2),
    actual_profit_margin numeric(5,2),
    actual_revenue numeric(15,2),
    actual_risk_level numeric(5,2),
    created_at timestamp(6) without time zone NOT NULL,
    notes text,
    realized_at timestamp(6) without time zone NOT NULL,
    business_id bigint NOT NULL,
    decision_id bigint NOT NULL,
    scenario_id bigint NOT NULL
);


--
-- Name: actual_outcome_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.actual_outcome ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actual_outcome_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_dna; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_dna (
    id bigint NOT NULL,
    competitive_strength numeric(5,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_acquisition_cost numeric(15,2) NOT NULL,
    customer_retention numeric(5,2) NOT NULL,
    digital_maturity numeric(5,2) NOT NULL,
    financial_stability numeric(5,2) NOT NULL,
    innovation_capability numeric(5,2) NOT NULL,
    last_updated timestamp(6) without time zone NOT NULL,
    market_growth numeric(5,2) NOT NULL,
    operational_efficiency numeric(5,2) NOT NULL,
    profit_margin numeric(5,2) NOT NULL,
    revenue numeric(15,2) NOT NULL,
    risk_level numeric(5,2) NOT NULL,
    business_id bigint NOT NULL
);


--
-- Name: business_dna_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.business_dna ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_dna_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: businesses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.businesses (
    id bigint NOT NULL,
    business_code character varying(255) NOT NULL,
    business_name character varying(255) NOT NULL,
    contact_email character varying(255),
    contact_phone character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255),
    industry character varying(255),
    location character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: businesses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.businesses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.businesses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: decision; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.decision (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    decision_maker character varying(100),
    decision_status character varying(50) NOT NULL,
    implemented_at timestamp(6) without time zone,
    notes text,
    business_id bigint NOT NULL,
    recommendation_id bigint,
    scenario_id bigint NOT NULL,
    simulation_id bigint NOT NULL
);


--
-- Name: decision_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.decision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.decision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dna_parameter_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dna_parameter_history (
    id bigint NOT NULL,
    changed_at timestamp(6) without time zone NOT NULL,
    new_value numeric(15,2),
    old_value numeric(15,2),
    parameter_name character varying(100) NOT NULL,
    reason character varying(255),
    business_dna_id bigint NOT NULL
);


--
-- Name: dna_parameter_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dna_parameter_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dna_parameter_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recommendation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recommendation (
    id bigint NOT NULL,
    action_statement text NOT NULL,
    confidence_score numeric(5,2),
    created_at timestamp(6) without time zone NOT NULL,
    expected_roi_percent numeric(5,2),
    rationale text,
    recommendation_type character varying(50) NOT NULL,
    risk_assessment character varying(50),
    status character varying(30),
    business_id bigint NOT NULL,
    scenario_id bigint NOT NULL,
    simulation_id bigint NOT NULL
);


--
-- Name: recommendation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recommendation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recommendation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scenario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scenario (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    demand_change_percent numeric(5,2),
    marketing_spend_change_percent numeric(5,2),
    price_change_percent numeric(5,2),
    scenario_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    supplier_cost_change_percent numeric(5,2),
    business_id bigint NOT NULL,
    business_dna_id bigint NOT NULL,
    twin_snapshot_id bigint NOT NULL,
    CONSTRAINT scenario_scenario_type_check CHECK (((scenario_type)::text = ANY ((ARRAY['PRICE_CHANGE'::character varying, 'MARKETING_CHANGE'::character varying, 'SUPPLIER_COST_CHANGE'::character varying, 'DEMAND_SHOCK'::character varying])::text[])))
);


--
-- Name: scenario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scenario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scenario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: simulation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.simulation (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    explanation_steps text,
    overall_impact character varying(50),
    profit_margin_impact_percent numeric(5,2),
    projected_customer_acquisition_cost numeric(10,2),
    projected_customer_retention numeric(5,2),
    projected_operational_efficiency numeric(5,2),
    projected_profit_margin numeric(5,2),
    projected_revenue numeric(15,2),
    projected_risk_level numeric(5,2),
    revenue_impact_percent numeric(5,2),
    risk_impact_percent numeric(5,2),
    summary text,
    business_id bigint NOT NULL,
    scenario_id bigint NOT NULL,
    twin_snapshot_id bigint NOT NULL
);


--
-- Name: simulation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.simulation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.simulation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: twin_evolution; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.twin_evolution (
    id bigint NOT NULL,
    applied_at timestamp(6) without time zone NOT NULL,
    cac_variance_percent numeric(5,2),
    calibration_action text,
    created_at timestamp(6) without time zone NOT NULL,
    evolution_insight text,
    overall_accuracy_percent numeric(5,2),
    profit_margin_variance_points numeric(5,2),
    revenue_variance_percent numeric(5,2),
    actual_outcome_id bigint NOT NULL,
    business_id bigint NOT NULL,
    decision_id bigint NOT NULL,
    simulation_id bigint NOT NULL
);


--
-- Name: twin_evolution_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.twin_evolution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.twin_evolution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: twin_snapshot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.twin_snapshot (
    id bigint NOT NULL,
    competitive_strength numeric(5,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    customer_acquisition_cost numeric(15,2) NOT NULL,
    customer_retention numeric(5,2) NOT NULL,
    digital_maturity numeric(5,2) NOT NULL,
    financial_stability numeric(5,2) NOT NULL,
    innovation_capability numeric(5,2) NOT NULL,
    market_growth numeric(5,2) NOT NULL,
    operational_efficiency numeric(5,2) NOT NULL,
    profit_margin numeric(5,2) NOT NULL,
    revenue numeric(15,2) NOT NULL,
    risk_level numeric(5,2) NOT NULL,
    snapshot_time timestamp(6) without time zone NOT NULL,
    business_id bigint NOT NULL,
    business_dna_id bigint NOT NULL
);


--
-- Name: twin_snapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.twin_snapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.twin_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: actual_outcome actual_outcome_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actual_outcome
    ADD CONSTRAINT actual_outcome_pkey PRIMARY KEY (id);


--
-- Name: business_dna business_dna_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_dna
    ADD CONSTRAINT business_dna_pkey PRIMARY KEY (id);


--
-- Name: businesses businesses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.businesses
    ADD CONSTRAINT businesses_pkey PRIMARY KEY (id);


--
-- Name: decision decision_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision
    ADD CONSTRAINT decision_pkey PRIMARY KEY (id);


--
-- Name: dna_parameter_history dna_parameter_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dna_parameter_history
    ADD CONSTRAINT dna_parameter_history_pkey PRIMARY KEY (id);


--
-- Name: recommendation recommendation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation
    ADD CONSTRAINT recommendation_pkey PRIMARY KEY (id);


--
-- Name: scenario scenario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario
    ADD CONSTRAINT scenario_pkey PRIMARY KEY (id);


--
-- Name: simulation simulation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation
    ADD CONSTRAINT simulation_pkey PRIMARY KEY (id);


--
-- Name: twin_evolution twin_evolution_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twin_evolution
    ADD CONSTRAINT twin_evolution_pkey PRIMARY KEY (id);


--
-- Name: twin_snapshot twin_snapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twin_snapshot
    ADD CONSTRAINT twin_snapshot_pkey PRIMARY KEY (id);


--
-- Name: business_dna uk7bke6q11nxgy5jqgx6pt4s38o; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_dna
    ADD CONSTRAINT uk7bke6q11nxgy5jqgx6pt4s38o UNIQUE (business_id);


--
-- Name: businesses uk7tg69y8b76x07tkrufpoya0ub; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.businesses
    ADD CONSTRAINT uk7tg69y8b76x07tkrufpoya0ub UNIQUE (business_code);


--
-- Name: scenario fk3pn50xh8ow6nlw2w65n5yj0g1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario
    ADD CONSTRAINT fk3pn50xh8ow6nlw2w65n5yj0g1 FOREIGN KEY (business_id) REFERENCES public.businesses(id);


--
-- Name: decision fk55luqdnwirwit99btuffh9lvo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision
    ADD CONSTRAINT fk55luqdnwirwit99btuffh9lvo FOREIGN KEY (business_id) REFERENCES public.businesses(id);


--
-- Name: recommendation fk5c53uokdxou2uejvm8ydog4mo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation
    ADD CONSTRAINT fk5c53uokdxou2uejvm8ydog4mo FOREIGN KEY (simulation_id) REFERENCES public.simulation(id);


--
-- Name: actual_outcome fk5eh044ty83rvcb9hie62kc7ev; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actual_outcome
    ADD CONSTRAINT fk5eh044ty83rvcb9hie62kc7ev FOREIGN KEY (business_id) REFERENCES public.businesses(id);


--
-- Name: decision fk5p7knlm0oy25w7di1iifilebt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision
    ADD CONSTRAINT fk5p7knlm0oy25w7di1iifilebt FOREIGN KEY (simulation_id) REFERENCES public.simulation(id);


--
-- Name: actual_outcome fk5pmy7wm5u1bs405x13lw2is7w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actual_outcome
    ADD CONSTRAINT fk5pmy7wm5u1bs405x13lw2is7w FOREIGN KEY (scenario_id) REFERENCES public.scenario(id);


--
-- Name: twin_evolution fk6ljpsx7vang877j97muq28a8k; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twin_evolution
    ADD CONSTRAINT fk6ljpsx7vang877j97muq28a8k FOREIGN KEY (decision_id) REFERENCES public.decision(id);


--
-- Name: twin_snapshot fkaiqyqgieed9vq108u5uu4o0cy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twin_snapshot
    ADD CONSTRAINT fkaiqyqgieed9vq108u5uu4o0cy FOREIGN KEY (business_dna_id) REFERENCES public.business_dna(id);


--
-- Name: recommendation fkaykikv9v5qxw28bih3i7dp6h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation
    ADD CONSTRAINT fkaykikv9v5qxw28bih3i7dp6h FOREIGN KEY (scenario_id) REFERENCES public.scenario(id);


--
-- Name: business_dna fkbu5eoh9xej6me1fc9htn5aeqi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_dna
    ADD CONSTRAINT fkbu5eoh9xej6me1fc9htn5aeqi FOREIGN KEY (business_id) REFERENCES public.businesses(id);


--
-- Name: twin_evolution fkd36ngyb4a9qcg1n625f1cjaok; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twin_evolution
    ADD CONSTRAINT fkd36ngyb4a9qcg1n625f1cjaok FOREIGN KEY (actual_outcome_id) REFERENCES public.actual_outcome(id);


--
-- Name: scenario fkesj1w683coj2briu29q8cgk4t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario
    ADD CONSTRAINT fkesj1w683coj2briu29q8cgk4t FOREIGN KEY (business_dna_id) REFERENCES public.business_dna(id);


--
-- Name: twin_evolution fki1fk9istmv3ql5lkhmj0xgn79; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twin_evolution
    ADD CONSTRAINT fki1fk9istmv3ql5lkhmj0xgn79 FOREIGN KEY (business_id) REFERENCES public.businesses(id);


--
-- Name: scenario fkir0goe14p1jsi2myshkrg3gll; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scenario
    ADD CONSTRAINT fkir0goe14p1jsi2myshkrg3gll FOREIGN KEY (twin_snapshot_id) REFERENCES public.twin_snapshot(id);


--
-- Name: actual_outcome fkj9qmhjdhfswcio8t47a7o1enl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.actual_outcome
    ADD CONSTRAINT fkj9qmhjdhfswcio8t47a7o1enl FOREIGN KEY (decision_id) REFERENCES public.decision(id);


--
-- Name: dna_parameter_history fklpqcucc33avfpxxawl0a9wrfp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dna_parameter_history
    ADD CONSTRAINT fklpqcucc33avfpxxawl0a9wrfp FOREIGN KEY (business_dna_id) REFERENCES public.business_dna(id);


--
-- Name: simulation fkn4kabs5e401gno2i6itkxabvr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation
    ADD CONSTRAINT fkn4kabs5e401gno2i6itkxabvr FOREIGN KEY (business_id) REFERENCES public.businesses(id);


--
-- Name: recommendation fkn538d0xrbc10fe1158o9vwvca; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recommendation
    ADD CONSTRAINT fkn538d0xrbc10fe1158o9vwvca FOREIGN KEY (business_id) REFERENCES public.businesses(id);


--
-- Name: decision fknp79216b762xvukaifmt0fw08; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision
    ADD CONSTRAINT fknp79216b762xvukaifmt0fw08 FOREIGN KEY (recommendation_id) REFERENCES public.recommendation(id);


--
-- Name: twin_snapshot fkp7qfk1v0qkqit6yrp9ot48hsf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twin_snapshot
    ADD CONSTRAINT fkp7qfk1v0qkqit6yrp9ot48hsf FOREIGN KEY (business_id) REFERENCES public.businesses(id);


--
-- Name: simulation fkpbksllm4h1iqala63gilfe0i5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation
    ADD CONSTRAINT fkpbksllm4h1iqala63gilfe0i5 FOREIGN KEY (scenario_id) REFERENCES public.scenario(id);


--
-- Name: simulation fkpxq6969r056xkl44flia5afvs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.simulation
    ADD CONSTRAINT fkpxq6969r056xkl44flia5afvs FOREIGN KEY (twin_snapshot_id) REFERENCES public.twin_snapshot(id);


--
-- Name: decision fkrg70xo9h9xla7326rf2vksgfi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.decision
    ADD CONSTRAINT fkrg70xo9h9xla7326rf2vksgfi FOREIGN KEY (scenario_id) REFERENCES public.scenario(id);


--
-- Name: twin_evolution fks01qwdpbxpb5seb3y8ii3i9np; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.twin_evolution
    ADD CONSTRAINT fks01qwdpbxpb5seb3y8ii3i9np FOREIGN KEY (simulation_id) REFERENCES public.simulation(id);


--
-- PostgreSQL database dump complete
--

\unrestrict mGQTcto3XvUQrP0XhjmQf7OnU7SjeYhYg35k4LgZJoWHZlCVPaL2zZ7wUrhsSRa

