spring.application.name=twiniq-backend

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/twiniq
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Actuator
management.endpoints.web.exposure.include=health,info